### ISSUE TITLE
Files missing

### ISSUE THREAD

**Issue by kaikoveritch** [unige-semantics-2017/heidi#1]
It appears there are no "Test" or "Source" folders and files. Should we import those from elsewhere ?

**Comment by saucisson** [comment]
As you are free to do the TP in Swift or Prolog, you have to create the sources yourselves.
In swift, run the following command in the `heidi` directory:

```sh
$ swift package init
```

In prolog, you have to follow [this guide](http://www.swi-prolog.org/pldoc/doc_for?object=section('packages/plunit.html')).

**Comment by kaikoveritch** [comment]
Noted ! 

(I'll leave this issue opened for now in case anybody wants to read it)

**Comment by kaikoveritch** [comment]
Hum... Actually... How are we supposed to do that on GNU/Linux ? We have not installed Swift. Is there a Docker equivalent ?

**Comment by saucisson** [comment]
You can take the Dockerfile from the previous TP (for the swift version).

**Comment by Aolledin** [comment]
Il faudrait quand même les mettre, pour faciliter l'exercice.

**Comment by saucisson** [comment]
`Sources` and `Tests` files have now been added.
