### ISSUE TITLE
Précision énoncé

### ISSUE THREAD

**Issue by arthurdeschamps** [unige-semantics-2017/heidi#2]
Bonjour.
Je ne comprends pas la question: "Est-il possible d'obtenir la liste de tous les problèmes possibles ?".  Qu'entendez vous par un problème ?

**Comment by saucisson** [comment]
De toutes les séquences d'ordres interprétées différemment si on supprime les pauses entre les ordres.

**Comment by arthurdeschamps** [comment]
D'accord, je vois. 

Donc dans la preuve, doit-on vérifier que la solution est unique ?

Ma clause "proof" retourne "true" car en traduisant une instruction du langage d'Heidi à celui de Tita et retour, on trouve bien la même instruction qu'au début, mais d'autres aussi.

**Comment by saucisson** [comment]
Peux-tu m'expliquer un peu mieux ta question s'il te plaît ?

**Comment by arthurdeschamps** [comment]
Alors, pour répondre à la question "Preuve" de l'énoncé, j'ai créé une règle Prolog de la forme suivante:
```
proof(X) :-
    terme_heidi(X),
    heidi_to_tita(X, Y), % Romanche to sifflets
    tita_to_heidi(Y, Z), % Back to romanche
    X = Z. % Verification
```
Cette règle, appliquée à l'exemple demandé, fonctionne car elle trouve bien un candidat Z tel que X = Z, mais si je décide d'afficher Z avec un 'write(Z)', j'obtiens aussi d'autres valeurs. Ceci s'explique par le fait qu'une traduction de sifflements au langage d'Heidi est ambigüe, dans certain cas.

Ma question est donc, est-ce que la règle `proof(X)` doit échouer s'il existe plusieurs valeurs possibles pour Z ?

**Comment by saucisson** [comment]
Oui, il faudrait qu'elle échoue.

**Comment by arthurdeschamps** [comment]
Ok merci.
